// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	surveyPlaces: () => __TAURI_INVOKE<SurveyPlaces>("survey_places"),
	/**
	 *  Walk a volume or a folder. Progress streams through `on_progress`; the
	 *  folded tree comes back when the walk ends (or is stopped with "show"),
	 *  compared with the last survey of the same place. A walk that finished is
	 *  kept as that place's snapshot for the next one.
	 */
	survey: (target: SurveyTarget, onProgress: Channel<SurveyProgress>) => typedError<SurveyResult_Serialize, AppError>(__TAURI_INVOKE("survey", { target, onProgress })),
	/**
	 *  End the running walk early: `cancel` throws the result away, otherwise
	 *  what has been listed so far is shown.
	 */
	surveyStop: (cancel: boolean) => __TAURI_INVOKE<void>("survey_stop", { cancel }),
	/**  Show an item of the current survey in Finder (Explorer, Files). */
	reveal: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal", { path })),
	/**
	 *  Expand a folded folder of the current survey — show what is inside it,
	 *  from the tree the walk already holds — and return the survey as it now
	 *  stands.
	 */
	expandFolder: (path: string) => typedError<SurveyResult_Serialize, AppError>(__TAURI_INVOKE("expand_folder", { path })),
	/**
	 *  Move an item of the current survey to the Trash, then return the survey as
	 *  it now stands. Refuses the surveyed root, folders the system or the account
	 *  depends on, and anything already in the Trash.
	 */
	moveToTrash: (path: string) => typedError<SurveyResult_Serialize, AppError>(__TAURI_INVOKE("move_to_trash", { path })),
	/**  Open the Full Disk Access pane of System Settings. */
	openPrivacySettings: () => typedError<null, AppError>(__TAURI_INVOKE("open_privacy_settings")),
	devOptions: () => __TAURI_INVOKE<DevOptions_Serialize>("dev_options"),
};

/* Types */
export type AppError = 
/**  The detail is the path (or the OS message) of what is missing. */
{ code: "NotFound"; detail: string } | { code: "Io"; detail: string } | { code: "Db"; detail: string } | 
/**  The user stopped the survey and asked for nothing to be shown. */
{ code: "Cancelled" } | 
/**  Another survey is still walking. */
{ code: "Busy" } | 
/**
 *  The app declined to do it; the detail says why, as a code the
 *  frontend words in the UI language.
 */
{ code: "Refused"; detail: Refusal } | 
/**  User-visible catch-all. Internal details belong in the logs, not here. */
{ code: "Internal" };

export type ChangePlace = {
	/**  Folder names from the survey's root down. */
	path: string[],
	was: number | null,
	now: number | null,
	/**  It was not there last time. */
	new: boolean,
};

/**  Development switches, read from the environment in debug builds only. */
export type DevOptions = DevOptions_Serialize | DevOptions_Deserialize;

/**  Development switches, read from the environment in debug builds only. */
export type DevOptions_Deserialize = {
	/**  `YISOBATH_SURVEY`: "volume", "home" or an absolute folder to survey on launch. */
	survey?: string | null,
	/**  `YISOBATH_PERF=1`: log frame timings to the app log every few seconds. */
	perf: boolean,
};

/**  Development switches, read from the environment in debug builds only. */
export type DevOptions_Serialize = {
	/**  `YISOBATH_SURVEY`: "volume", "home" or an absolute folder to survey on launch. */
	survey?: string | null,
	/**  `YISOBATH_PERF=1`: log frame timings to the app log every few seconds. */
	perf: boolean,
};

/**  The ten file types, in the order of `ISO_TYPE_KEYS` in the catalog. */
export type FileKind = "vid" | "img" | "aud" | "mdl" | "src" | "bin" | "vmi" | "arc" | "doc" | "sys";

/**
 *  Why the app declined to act on a path. Crosses IPC as a stable kebab-case
 *  code (`"in-trash"`); `src/lib/survey.ts` turns it into a sentence in the UI
 *  language, so adding a variant is a compile error there until it is worded.
 */
export type Refusal = 
/**  Nothing has been surveyed yet. */
"no-survey" | 
/**  Not an absolute path, or one that climbs out with `..`. */
"not-absolute" | 
/**  Outside the surveyed folder, or the surveyed folder itself. */
"outside-survey" | 
/**  A folder the system or the account depends on. */
"protected" | 
/**  Part of the sealed system. */
"system" | 
/**  Already in the Trash. */
"in-trash";

/**  What changed since the last survey of the same place. */
export type SurveyChange = {
	/**  When the previous survey finished, in milliseconds since the epoch. */
	since: number | null,
	/**  What the place held then. */
	was: number | null,
	/**  Where it grew most, largest growth first. */
	places: ChangePlace[],
};

/**  What the instrument shows about the surveyed place. */
export type SurveyMeta = SurveyMeta_Serialize | SurveyMeta_Deserialize;

/**  What the instrument shows about the surveyed place. */
export type SurveyMeta_Deserialize = {
	/**  "volume" for a whole disk, "folder" for anything else (home included). */
	kind: string,
	/**  The root's name: "Macintosh HD", or the folder's name. */
	name: string,
	/**  "Data", "Home folder" or "Folder". */
	role: string,
	fs: string,
	device: string,
	/**  Bytes the volume holds, and bytes still free. */
	capacity: number | null,
	free: number | null,
	/**  The absolute path that was walked. */
	root: string,
	/**  How the root reads at the start of a path: "~", "~/github", "/Volumes/X". */
	display: string,
	/**  Path from the root to the home folder, shown as "~" (volume surveys). */
	home?: string[] | null,
};

/**  What the instrument shows about the surveyed place. */
export type SurveyMeta_Serialize = {
	/**  "volume" for a whole disk, "folder" for anything else (home included). */
	kind: string,
	/**  The root's name: "Macintosh HD", or the folder's name. */
	name: string,
	/**  "Data", "Home folder" or "Folder". */
	role: string,
	fs: string,
	device: string,
	/**  Bytes the volume holds, and bytes still free. */
	capacity: number | null,
	free: number | null,
	/**  The absolute path that was walked. */
	root: string,
	/**  How the root reads at the start of a path: "~", "~/github", "/Volumes/X". */
	display: string,
	/**  Path from the root to the home folder, shown as "~" (volume surveys). */
	home?: string[] | null,
};

/**  A node in the shape `Volume` reads (`src/instrument/volume.ts`). */
export type SurveyNode = SurveyNode_Serialize | SurveyNode_Deserialize;

/**  A node in the shape `Volume` reads (`src/instrument/volume.ts`). */
export type SurveyNode_Deserialize = {
	name: string,
	/**  Open folders only. */
	children?: SurveyNode_Deserialize[] | null,
	/**  Leaves only; an open folder is the sum of its children. */
	bytes: number | null,
	/**  How many files a leaf stands for. */
	files: number | null,
	/**  How many folders a leaf stands for (a folded folder counts itself). */
	dirs: number | null,
	/**  Days since last modified (byte-weighted for folded pieces). */
	age: number | null,
	type: FileKind,
	/**  The loose files of a folder, gathered. */
	agg?: boolean,
	/**  A folder shown as one piece. */
	folded?: boolean,
	/**  A folded folder that shows more than one piece when expanded. */
	expandable?: boolean,
	dup?: string | null,
	tag?: string | null,
	/**  The folder could not be listed. */
	denied?: boolean,
};

/**  A node in the shape `Volume` reads (`src/instrument/volume.ts`). */
export type SurveyNode_Serialize = {
	name: string,
	/**  Open folders only. */
	children?: SurveyNode_Serialize[] | null,
	/**  Leaves only; an open folder is the sum of its children. */
	bytes: number | null,
	/**  How many files a leaf stands for. */
	files: number | null,
	/**  How many folders a leaf stands for (a folded folder counts itself). */
	dirs: number | null,
	/**  Days since last modified (byte-weighted for folded pieces). */
	age: number | null,
	type: FileKind,
	/**  The loose files of a folder, gathered. */
	agg?: boolean,
	/**  A folder shown as one piece. */
	folded?: boolean,
	/**  A folded folder that shows more than one piece when expanded. */
	expandable?: boolean,
	dup?: string | null,
	tag?: string | null,
	/**  The folder could not be listed. */
	denied?: boolean,
};

/**  What the start panel needs before anything is walked. */
export type SurveyPlaces = {
	/**  The boot volume's name ("Macintosh HD"). */
	volumeName: string,
	/**  The home folder, absolute. */
	home: string,
	fullDiskAccess: boolean,
	/**  Capacity and free space of the data volume. */
	capacity: number | null,
	free: number | null,
};

/**  Streamed while a walk runs. */
export type SurveyProgress = {
	files: number | null,
	dirs: number | null,
	bytes: number | null,
	current: string,
};

export type SurveyResult = SurveyResult_Serialize | SurveyResult_Deserialize;

export type SurveyResult_Deserialize = {
	root: SurveyNode_Deserialize,
	meta: SurveyMeta_Deserialize,
	stats: SurveyStats,
	/**  What changed since the last survey of this place; none the first time. */
	change?: SurveyChange | null,
};

export type SurveyResult_Serialize = {
	root: SurveyNode_Serialize,
	meta: SurveyMeta_Serialize,
	stats: SurveyStats,
	/**  What changed since the last survey of this place; none the first time. */
	change?: SurveyChange | null,
};

export type SurveyStats = {
	files: number | null,
	dirs: number | null,
	bytes: number | null,
	/**  Folders that could not be listed. */
	denied: number | null,
	/**  Folders skipped because they are another device. */
	mounts: number | null,
	/**  Extra hard links to a file counted once. */
	hardlinks: number | null,
	tookMs: number | null,
	/**  Stopped before the walk finished. */
	partial: boolean,
	/**  Nodes handed to the instrument, and the fold threshold that got there. */
	nodes: number | null,
	threshold: number | null,
	fullDiskAccess: boolean,
};

/**  What to survey. */
export type SurveyTarget = 
/**  The whole data volume (on macOS `/System/Volumes/Data`). */
{ kind: "volume" } | 
/**  The user's home folder. */
{ kind: "home" } | 
/**  Any folder. */
{ kind: "folder"; path: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

