// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Demo command kept from the scaffold so the index route has something to call. */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**
	 *  Milliseconds elapsed since the managed [`AppState`] was created.
	 * 
	 *  Demonstrates managed-state injection plus the `AppResult` error model
	 *  (this particular command never fails, but real ones will). Returned as
	 *  `f64` so it maps to a plain TS `number` — specta refuses to export 64-bit
	 *  integer types to avoid silent precision loss across the IPC boundary.
	 */
	uptimeMs: () => typedError<number | null, AppError>(__TAURI_INVOKE("uptime_ms")),
	/**
	 *  List the immediate children of a directory.
	 * 
	 *  Realistic starting point for an asset browser: filesystem errors map to a
	 *  typed [`AppError`](crate::error::AppError) through the `From<std::io::Error>`
	 *  impl, so the frontend gets `NotFound` vs `Io` rather than an opaque string.
	 */
	listDir: (path: string) => typedError<DirEntry[], AppError>(__TAURI_INVOKE("list_dir", { path })),
};

/* Types */
export type AppError = { code: "NotFound"; detail: string } | { code: "Io"; detail: string } | { code: "Db"; detail: string } | 
/**  User-visible catch-all. Internal details belong in the logs, not here. */
{ code: "Internal" };

/**  A single directory entry returned by [`list_dir`]. */
export type DirEntry = {
	name: string,
	path: string,
	is_dir: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

