import type { AppError } from "@/lib/bindings";

/**
 * The typed IPC error. `AppError` is generated by tauri-specta from the Rust
 * enum (`src-tauri/src/error.rs`) into `@/lib/bindings`; this re-export gives it
 * a stable, intention-revealing name and a place to hang frontend helpers.
 *
 * Branch on the stable `code` for UI/retry decisions; `detail` is for display
 * and logging only.
 */
export type CommandError = AppError;

/** Narrow an unknown thrown value (e.g. from a rejected `invoke`) to a CommandError. */
export function isCommandError(error: unknown): error is CommandError {
	return (
		typeof error === "object" &&
		error !== null &&
		"code" in error &&
		typeof (error as { code: unknown }).code === "string"
	);
}
